export const sampleMeals = [
  // CHICKEN
  { title: "Honey Garlic Chicken Thighs", description: "Sweet and savory chicken thighs with crispy skin.", cuisine: "American", skillLevel: "Easy", timeMinutes: 35, ageRanges: ["2-5", "6-10", "10-13"], dietaryFlags: ["gluten-free"], ingredients: ["Chicken thighs", "Honey", "Garlic", "Soy sauce", "Butter"] },
  { title: "Chicken Nuggets (Homemade)", description: "Crispy baked nuggets way better than frozen.", cuisine: "American", skillLevel: "Easy", timeMinutes: 30, ageRanges: ["2-5", "6-10"], dietaryFlags: [], ingredients: ["Chicken breast", "Breadcrumbs", "Egg", "Flour", "Paprika"] },
  { title: "Teriyaki Chicken Bowl", description: "Sweet teriyaki chicken over fluffy rice.", cuisine: "Asian", skillLevel: "Easy", timeMinutes: 25, ageRanges: ["6-10", "10-13"], dietaryFlags: [], ingredients: ["Chicken breast", "Rice", "Teriyaki sauce", "Broccoli", "Sesame seeds"] },
  { title: "Chicken Parmesan", description: "Crispy breaded chicken with melted mozzarella.", cuisine: "Italian", skillLevel: "Intermediate", timeMinutes: 40, ageRanges: ["6-10", "10-13"], dietaryFlags: [], ingredients: ["Chicken breast", "Breadcrumbs", "Marinara sauce", "Mozzarella", "Parmesan"] },
  { title: "BBQ Chicken Drumsticks", description: "Sticky sweet drumsticks kids love to hold.", cuisine: "American", skillLevel: "Easy", timeMinutes: 45, ageRanges: ["2-5", "6-10", "10-13"], dietaryFlags: ["gluten-free"], ingredients: ["Chicken drumsticks", "BBQ sauce", "Garlic powder", "Paprika"] },
  { title: "Chicken Fried Rice", description: "Better than takeout, ready in 20 minutes.", cuisine: "Asian", skillLevel: "Easy", timeMinutes: 20, ageRanges: ["2-5", "6-10", "10-13"], dietaryFlags: [], ingredients: ["Cooked rice", "Chicken", "Eggs", "Peas", "Carrots", "Soy sauce"] },
  { title: "Lemon Herb Chicken", description: "Bright and zesty baked chicken.", cuisine: "Mediterranean", skillLevel: "Easy", timeMinutes: 35, ageRanges: ["6-10", "10-13"], dietaryFlags: ["gluten-free"], ingredients: ["Chicken breast", "Lemon", "Olive oil", "Oregano", "Garlic"] },
  { title: "Chicken Alfredo Pasta", description: "Creamy pasta that disappears fast.", cuisine: "Italian", skillLevel: "Easy", timeMinutes: 25, ageRanges: ["2-5", "6-10", "10-13"], dietaryFlags: [], ingredients: ["Fettuccine", "Chicken breast", "Heavy cream", "Parmesan", "Garlic", "Butter"] },
  { title: "Chicken Tenders", description: "Classic crispy tenders with honey mustard.", cuisine: "American", skillLevel: "Easy", timeMinutes: 25, ageRanges: ["2-5", "6-10"], dietaryFlags: [], ingredients: ["Chicken tenderloins", "Flour", "Egg", "Breadcrumbs", "Salt"] },
  { title: "Greek Chicken Pita Pockets", description: "Fresh and healthy Mediterranean flavors.", cuisine: "Mediterranean", skillLevel: "Easy", timeMinutes: 20, ageRanges: ["6-10", "10-13"], dietaryFlags: [], ingredients: ["Chicken breast", "Pita bread", "Cucumber", "Tomato", "Feta", "Tzatziki"] },

  // BEEF
  { title: "Classic Cheeseburgers", description: "Juicy homemade burgers with all the fixings.", cuisine: "American", skillLevel: "Easy", timeMinutes: 25, ageRanges: ["6-10", "10-13"], dietaryFlags: [], ingredients: ["Ground beef", "Burger buns", "Cheese", "Lettuce", "Tomato", "Ketchup"] },
  { title: "Beef Tacos", description: "Seasoned ground beef in crunchy shells.", cuisine: "Mexican", skillLevel: "Easy", timeMinutes: 20, ageRanges: ["2-5", "6-10", "10-13"], dietaryFlags: [], ingredients: ["Ground beef", "Taco shells", "Cheese", "Lettuce", "Tomato", "Sour cream"] },
  { title: "Sloppy Joes", description: "Messy, delicious, and kid-approved.", cuisine: "American", skillLevel: "Easy", timeMinutes: 25, ageRanges: ["6-10", "10-13"], dietaryFlags: [], ingredients: ["Ground beef", "Tomato sauce", "Brown sugar", "Worcestershire sauce", "Hamburger buns"] },
  { title: "Beef Stir Fry", description: "Tender beef strips with colorful veggies.", cuisine: "Asian", skillLevel: "Intermediate", timeMinutes: 25, ageRanges: ["6-10", "10-13"], dietaryFlags: [], ingredients: ["Beef sirloin", "Bell peppers", "Broccoli", "Soy sauce", "Ginger", "Rice"] },
  { title: "Mini Meatloaf Cups", description: "Individual meatloaves kids can hold.", cuisine: "American", skillLevel: "Easy", timeMinutes: 35, ageRanges: ["2-5", "6-10"], dietaryFlags: [], ingredients: ["Ground beef", "Breadcrumbs", "Egg", "Ketchup", "Onion"] },
  { title: "Beef and Cheese Nachos", description: "Loaded nachos perfect for movie night.", cuisine: "Mexican", skillLevel: "Easy", timeMinutes: 20, ageRanges: ["6-10", "10-13"], dietaryFlags: [], ingredients: ["Ground beef", "Tortilla chips", "Cheese", "Jalapeños", "Sour cream", "Salsa"] },
  { title: "Korean Beef Rice Bowl", description: "Sweet and savory Korean-style beef.", cuisine: "Asian", skillLevel: "Easy", timeMinutes: 20, ageRanges: ["6-10", "10-13"], dietaryFlags: [], ingredients: ["Ground beef", "Rice", "Soy sauce", "Brown sugar", "Garlic", "Sesame oil"] },
  { title: "Beef Quesadillas", description: "Cheesy and filling quesadillas.", cuisine: "Mexican", skillLevel: "Easy", timeMinutes: 15, ageRanges: ["2-5", "6-10", "10-13"], dietaryFlags: [], ingredients: ["Ground beef", "Tortillas", "Cheese", "Bell peppers", "Onion"] },
  { title: "Simple Steak Bites", description: "Quick seared steak cubes with butter.", cuisine: "American", skillLevel: "Intermediate", timeMinutes: 15, ageRanges: ["6-10", "10-13"], dietaryFlags: ["gluten-free"], ingredients: ["Sirloin steak", "Butter", "Garlic", "Salt", "Pepper"] },
  { title: "Beef Stroganoff", description: "Creamy beef over egg noodles.", cuisine: "American", skillLevel: "Intermediate", timeMinutes: 30, ageRanges: ["6-10", "10-13"], dietaryFlags: [], ingredients: ["Beef sirloin", "Egg noodles", "Mushrooms", "Sour cream", "Beef broth"] },

  // TURKEY
  { title: "Turkey Meatballs", description: "Lighter meatballs that are just as tasty.", cuisine: "Italian", skillLevel: "Easy", timeMinutes: 30, ageRanges: ["2-5", "6-10"], dietaryFlags: [], ingredients: ["Ground turkey", "Breadcrumbs", "Egg", "Parmesan", "Marinara sauce"] },
  { title: "Turkey Tacos", description: "Healthier taco option kids still love.", cuisine: "Mexican", skillLevel: "Easy", timeMinutes: 20, ageRanges: ["2-5", "6-10", "10-13"], dietaryFlags: [], ingredients: ["Ground turkey", "Taco seasoning", "Tortillas", "Cheese", "Lettuce"] },
  { title: "Turkey Burgers", description: "Lean and flavorful burger patties.", cuisine: "American", skillLevel: "Easy", timeMinutes: 25, ageRanges: ["6-10", "10-13"], dietaryFlags: [], ingredients: ["Ground turkey", "Burger buns", "Cheese", "Avocado", "Lettuce"] },
  { title: "Turkey and Rice Casserole", description: "Comforting one-dish dinner.", cuisine: "American", skillLevel: "Easy", timeMinutes: 45, ageRanges: ["2-5", "6-10"], dietaryFlags: [], ingredients: ["Ground turkey", "Rice", "Cream of mushroom soup", "Cheese", "Peas"] },
  { title: "Turkey Sausage Pasta", description: "Quick pasta with Italian turkey sausage.", cuisine: "Italian", skillLevel: "Easy", timeMinutes: 25, ageRanges: ["6-10", "10-13"], dietaryFlags: [], ingredients: ["Turkey sausage", "Penne pasta", "Marinara sauce", "Spinach", "Parmesan"] },

  // PORK
  { title: "Pork Chops with Applesauce", description: "Classic combo kids always enjoy.", cuisine: "American", skillLevel: "Easy", timeMinutes: 25, ageRanges: ["2-5", "6-10"], dietaryFlags: ["gluten-free"], ingredients: ["Pork chops", "Applesauce", "Salt", "Pepper", "Olive oil"] },
  { title: "Sweet and Sour Pork", description: "Colorful pork with tangy sauce.", cuisine: "Asian", skillLevel: "Intermediate", timeMinutes: 30, ageRanges: ["6-10", "10-13"], dietaryFlags: [], ingredients: ["Pork tenderloin", "Pineapple", "Bell peppers", "Sweet and sour sauce", "Rice"] },
  { title: "Pulled Pork Sandwiches", description: "Tender slow-cooked pork on soft buns.", cuisine: "American", skillLevel: "Easy", timeMinutes: 240, ageRanges: ["6-10", "10-13"], dietaryFlags: [], ingredients: ["Pork shoulder", "BBQ sauce", "Hamburger buns", "Coleslaw"] },
  { title: "Pork Fried Rice", description: "Quick weeknight fried rice with pork.", cuisine: "Asian", skillLevel: "Easy", timeMinutes: 20, ageRanges: ["2-5", "6-10", "10-13"], dietaryFlags: [], ingredients: ["Pork tenderloin", "Rice", "Eggs", "Peas", "Carrots", "Soy sauce"] },
  { title: "Bacon Mac and Cheese", description: "Classic mac and cheese with crispy bacon.", cuisine: "American", skillLevel: "Easy", timeMinutes: 25, ageRanges: ["2-5", "6-10", "10-13"], dietaryFlags: [], ingredients: ["Macaroni", "Cheese", "Bacon", "Milk", "Butter"] },
  { title: "Pork Carnitas Tacos", description: "Tender slow-cooked pork for tacos.", cuisine: "Mexican", skillLevel: "Easy", timeMinutes: 180, ageRanges: ["6-10", "10-13"], dietaryFlags: ["gluten-free"], ingredients: ["Pork shoulder", "Orange juice", "Cumin", "Tortillas", "Cilantro", "Onion"] },

  // FISH
  { title: "Fish Sticks (Homemade)", description: "Crispy baked fish sticks kids love.", cuisine: "American", skillLevel: "Easy", timeMinutes: 25, ageRanges: ["2-5", "6-10"], dietaryFlags: [], ingredients: ["White fish fillets", "Breadcrumbs", "Egg", "Flour", "Lemon"] },
  { title: "Salmon Teriyaki", description: "Glazed salmon with sweet teriyaki.", cuisine: "Asian", skillLevel: "Easy", timeMinutes: 20, ageRanges: ["6-10", "10-13"], dietaryFlags: ["gluten-free"], ingredients: ["Salmon fillets", "Teriyaki sauce", "Rice", "Broccoli"] },
  { title: "Fish Tacos", description: "Light and fresh with creamy sauce.", cuisine: "Mexican", skillLevel: "Easy", timeMinutes: 20, ageRanges: ["6-10", "10-13"], dietaryFlags: [], ingredients: ["White fish", "Tortillas", "Cabbage", "Lime", "Sour cream"] },
  { title: "Lemon Butter Tilapia", description: "Mild white fish with butter sauce.", cuisine: "American", skillLevel: "Easy", timeMinutes: 15, ageRanges: ["6-10", "10-13"], dietaryFlags: ["gluten-free"], ingredients: ["Tilapia fillets", "Butter", "Lemon", "Garlic", "Parsley"] },
  { title: "Shrimp Alfredo", description: "Creamy pasta with succulent shrimp.", cuisine: "Italian", skillLevel: "Easy", timeMinutes: 25, ageRanges: ["6-10", "10-13"], dietaryFlags: [], ingredients: ["Shrimp", "Fettuccine", "Heavy cream", "Parmesan", "Garlic"] },

  // VEGETARIAN
  { title: "Cheese Pizza (Homemade)", description: "Simple pizza with your favorite toppings.", cuisine: "Italian", skillLevel: "Intermediate", timeMinutes: 35, ageRanges: ["2-5", "6-10", "10-13"], dietaryFlags: ["vegetarian"], ingredients: ["Pizza dough", "Tomato sauce", "Mozzarella", "Olive oil", "Basil"] },
  { title: "Grilled Cheese Sandwiches", description: "Crispy, buttery, cheesy perfection.", cuisine: "American", skillLevel: "Easy", timeMinutes: 10, ageRanges: ["2-5", "6-10"], dietaryFlags: ["vegetarian"], ingredients: ["Bread", "Butter", "Cheese"] },
  { title: "Mac and Cheese", description: "Creamy homemade mac and cheese.", cuisine: "American", skillLevel: "Easy", timeMinutes: 20, ageRanges: ["2-5", "6-10", "10-13"], dietaryFlags: ["vegetarian"], ingredients: ["Macaroni", "Cheese", "Milk", "Butter", "Flour"] },
  { title: "Cheese Quesadillas", description: "Simple cheesy quesadillas.", cuisine: "Mexican", skillLevel: "Easy", timeMinutes: 10, ageRanges: ["2-5", "6-10"], dietaryFlags: ["vegetarian"], ingredients: ["Tortillas", "Cheese", "Butter"] },
  { title: "Veggie Fried Rice", description: "Colorful vegetable fried rice.", cuisine: "Asian", skillLevel: "Easy", timeMinutes: 20, ageRanges: ["2-5", "6-10", "10-13"], dietaryFlags: ["vegetarian"], ingredients: ["Rice", "Eggs", "Peas", "Carrots", "Soy sauce", "Sesame oil"] },
  { title: "Bean and Cheese Burritos", description: "Filling and protein-packed burritos.", cuisine: "Mexican", skillLevel: "Easy", timeMinutes: 15, ageRanges: ["2-5", "6-10", "10-13"], dietaryFlags: ["vegetarian"], ingredients: ["Tortillas", "Refried beans", "Cheese", "Rice", "Sour cream"] },
  { title: "Pasta Primavera", description: "Pasta loaded with fresh vegetables.", cuisine: "Italian", skillLevel: "Easy", timeMinutes: 25, ageRanges: ["6-10", "10-13"], dietaryFlags: ["vegetarian"], ingredients: ["Penne", "Zucchini", "Bell peppers", "Tomatoes", "Parmesan", "Olive oil"] },
  { title: "Vegetable Quesadillas", description: "Loaded with veggies and cheese.", cuisine: "Mexican", skillLevel: "Easy", timeMinutes: 15, ageRanges: ["6-10", "10-13"], dietaryFlags: ["vegetarian"], ingredients: ["Tortillas", "Cheese", "Bell peppers", "Onion", "Mushrooms"] },
  { title: "Caprese Pasta", description: "Fresh tomatoes, mozzarella, and basil.", cuisine: "Italian", skillLevel: "Easy", timeMinutes: 20, ageRanges: ["6-10", "10-13"], dietaryFlags: ["vegetarian"], ingredients: ["Pasta", "Cherry tomatoes", "Fresh mozzarella", "Basil", "Olive oil"] },
  { title: "Black Bean Tacos", description: "Hearty and satisfying meatless tacos.", cuisine: "Mexican", skillLevel: "Easy", timeMinutes: 15, ageRanges: ["2-5", "6-10", "10-13"], dietaryFlags: ["vegetarian"], ingredients: ["Black beans", "Tortillas", "Cheese", "Lettuce", "Salsa", "Sour cream"] },

  // PASTA
  { title: "Butter Noodles", description: "Simple buttery pasta kids devour.", cuisine: "American", skillLevel: "Easy", timeMinutes: 15, ageRanges: ["2-5", "6-10"], dietaryFlags: ["vegetarian"], ingredients: ["Egg noodles", "Butter", "Parmesan", "Salt"] },
  { title: "Spaghetti with Meat Sauce", description: "Classic spaghetti with hearty sauce.", cuisine: "Italian", skillLevel: "Easy", timeMinutes: 30, ageRanges: ["2-5", "6-10", "10-13"], dietaryFlags: [], ingredients: ["Spaghetti", "Ground beef", "Tomato sauce", "Onion", "Garlic"] },
  { title: "Baked Ziti", description: "Cheesy pasta bake everyone loves.", cuisine: "Italian", skillLevel: "Intermediate", timeMinutes: 45, ageRanges: ["6-10", "10-13"], dietaryFlags: [], ingredients: ["Ziti pasta", "Ricotta", "Mozzarella", "Marinara sauce", "Parmesan"] },
  { title: "Pesto Pasta", description: "Quick and flavorful basil pesto pasta.", cuisine: "Italian", skillLevel: "Easy", timeMinutes: 15, ageRanges: ["6-10", "10-13"], dietaryFlags: ["vegetarian"], ingredients: ["Pasta", "Basil pesto", "Parmesan", "Cherry tomatoes"] },
  { title: "Ravioli with Butter Sage", description: "Store-bought ravioli elevated.", cuisine: "Italian", skillLevel: "Easy", timeMinutes: 15, ageRanges: ["2-5", "6-10"], dietaryFlags: ["vegetarian"], ingredients: ["Cheese ravioli", "Butter", "Sage", "Parmesan"] },
  { title: "Lasagna", description: "Layered pasta with meat and cheese.", cuisine: "Italian", skillLevel: "Intermediate", timeMinutes: 75, ageRanges: ["6-10", "10-13"], dietaryFlags: [], ingredients: ["Lasagna noodles", "Ground beef", "Ricotta", "Mozzarella", "Marinara sauce"] },

  // TACOS & MEXICAN
  { title: "Breakfast Burritos", description: "Eggs, cheese, and bacon wrapped up.", cuisine: "Mexican", skillLevel: "Easy", timeMinutes: 20, ageRanges: ["6-10", "10-13"], dietaryFlags: [], ingredients: ["Tortillas", "Eggs", "Cheese", "Bacon", "Salsa"] },
  { title: "Enchiladas", description: "Rolled tortillas with cheesy sauce.", cuisine: "Mexican", skillLevel: "Intermediate", timeMinutes: 40, ageRanges: ["6-10", "10-13"], dietaryFlags: [], ingredients: ["Tortillas", "Chicken", "Enchilada sauce", "Cheese", "Sour cream"] },
  { title: "Taco Salad", description: "All the taco flavors in a bowl.", cuisine: "Mexican", skillLevel: "Easy", timeMinutes: 20, ageRanges: ["6-10", "10-13"], dietaryFlags: ["gluten-free"], ingredients: ["Ground beef", "Lettuce", "Tomatoes", "Cheese", "Tortilla chips", "Sour cream"] },
  { title: "Nachos Supreme", description: "Fully loaded nachos with everything.", cuisine: "Mexican", skillLevel: "Easy", timeMinutes: 20, ageRanges: ["6-10", "10-13"], dietaryFlags: [], ingredients: ["Tortilla chips", "Ground beef", "Cheese", "Black beans", "Jalapeños", "Sour cream"] },

  // RICE BOWLS
  { title: "Chicken Burrito Bowl", description: "Chipotle-style bowl at home.", cuisine: "Mexican", skillLevel: "Easy", timeMinutes: 25, ageRanges: ["6-10", "10-13"], dietaryFlags: ["gluten-free"], ingredients: ["Chicken", "Rice", "Black beans", "Corn", "Salsa", "Cheese", "Sour cream"] },
  { title: "Hawaiian Chicken Bowl", description: "Sweet pineapple chicken over rice.", cuisine: "American", skillLevel: "Easy", timeMinutes: 25, ageRanges: ["6-10", "10-13"], dietaryFlags: ["gluten-free"], ingredients: ["Chicken", "Rice", "Pineapple", "BBQ sauce", "Red onion"] },
  { title: "Sesame Chicken Bowl", description: "Crispy chicken with sesame glaze.", cuisine: "Asian", skillLevel: "Intermediate", timeMinutes: 30, ageRanges: ["6-10", "10-13"], dietaryFlags: [], ingredients: ["Chicken", "Rice", "Broccoli", "Sesame sauce", "Sesame seeds"] },

  // SHEET PAN
  { title: "Sheet Pan Fajitas", description: "Easy fajitas with minimal cleanup.", cuisine: "Mexican", skillLevel: "Easy", timeMinutes: 30, ageRanges: ["6-10", "10-13"], dietaryFlags: ["gluten-free"], ingredients: ["Chicken", "Bell peppers", "Onion", "Fajita seasoning", "Tortillas"] },
  { title: "Sheet Pan Sausage and Veggies", description: "One pan dinner with smoked sausage.", cuisine: "American", skillLevel: "Easy", timeMinutes: 30, ageRanges: ["6-10", "10-13"], dietaryFlags: ["gluten-free"], ingredients: ["Smoked sausage", "Potatoes", "Bell peppers", "Onion", "Olive oil"] },
  { title: "Sheet Pan Salmon", description: "Healthy salmon with roasted vegetables.", cuisine: "American", skillLevel: "Easy", timeMinutes: 25, ageRanges: ["6-10", "10-13"], dietaryFlags: ["gluten-free"], ingredients: ["Salmon", "Asparagus", "Cherry tomatoes", "Lemon", "Olive oil"] },
  { title: "Sheet Pan BBQ Chicken", description: "Sticky BBQ chicken with potatoes.", cuisine: "American", skillLevel: "Easy", timeMinutes: 35, ageRanges: ["2-5", "6-10", "10-13"], dietaryFlags: ["gluten-free"], ingredients: ["Chicken thighs", "Baby potatoes", "BBQ sauce", "Green beans"] },

  // SLOW COOKER
  { title: "Slow Cooker Pot Roast", description: "Fall-apart tender beef roast.", cuisine: "American", skillLevel: "Easy", timeMinutes: 480, ageRanges: ["6-10", "10-13"], dietaryFlags: ["gluten-free"], ingredients: ["Chuck roast", "Potatoes", "Carrots", "Onion", "Beef broth"] },
  { title: "Slow Cooker Chicken Tacos", description: "Shredded chicken for easy tacos.", cuisine: "Mexican", skillLevel: "Easy", timeMinutes: 360, ageRanges: ["2-5", "6-10", "10-13"], dietaryFlags: ["gluten-free"], ingredients: ["Chicken breast", "Salsa", "Taco seasoning", "Tortillas", "Cheese"] },
  { title: "Slow Cooker Chili", description: "Hearty chili with beans and beef.", cuisine: "American", skillLevel: "Easy", timeMinutes: 360, ageRanges: ["6-10", "10-13"], dietaryFlags: ["gluten-free"], ingredients: ["Ground beef", "Kidney beans", "Tomatoes", "Chili powder", "Onion"] },
  { title: "Slow Cooker BBQ Ribs", description: "Tender fall-off-the-bone ribs.", cuisine: "American", skillLevel: "Easy", timeMinutes: 420, ageRanges: ["6-10", "10-13"], dietaryFlags: ["gluten-free"], ingredients: ["Pork ribs", "BBQ sauce", "Brown sugar", "Garlic powder"] },

  // AIR FRYER
  { title: "Air Fryer Chicken Wings", description: "Crispy wings without deep frying.", cuisine: "American", skillLevel: "Easy", timeMinutes: 25, ageRanges: ["6-10", "10-13"], dietaryFlags: ["gluten-free"], ingredients: ["Chicken wings", "Salt", "Pepper", "Garlic powder", "Buffalo sauce"] },
  { title: "Air Fryer Chicken Tenders", description: "Extra crispy tenders in minutes.", cuisine: "American", skillLevel: "Easy", timeMinutes: 15, ageRanges: ["2-5", "6-10"], dietaryFlags: [], ingredients: ["Chicken tenderloins", "Breadcrumbs", "Egg", "Flour"] },
  { title: "Air Fryer Fish and Chips", description: "Classic fish and chips made healthier.", cuisine: "American", skillLevel: "Easy", timeMinutes: 25, ageRanges: ["6-10", "10-13"], dietaryFlags: [], ingredients: ["White fish", "Frozen fries", "Breadcrumbs", "Egg", "Tartar sauce"] },
  { title: "Air Fryer Mozzarella Sticks", description: "Gooey cheese sticks with marinara.", cuisine: "American", skillLevel: "Easy", timeMinutes: 10, ageRanges: ["2-5", "6-10", "10-13"], dietaryFlags: ["vegetarian"], ingredients: ["Mozzarella sticks", "Breadcrumbs", "Egg", "Marinara sauce"] },

  // BREAKFAST FOR DINNER
  { title: "Pancakes", description: "Fluffy pancakes with maple syrup.", cuisine: "American", skillLevel: "Easy", timeMinutes: 20, ageRanges: ["2-5", "6-10", "10-13"], dietaryFlags: ["vegetarian"], ingredients: ["Flour", "Eggs", "Milk", "Butter", "Maple syrup"] },
  { title: "French Toast", description: "Cinnamon-sugar coated toast.", cuisine: "American", skillLevel: "Easy", timeMinutes: 15, ageRanges: ["2-5", "6-10", "10-13"], dietaryFlags: ["vegetarian"], ingredients: ["Bread", "Eggs", "Milk", "Cinnamon", "Vanilla", "Maple syrup"] },
  { title: "Scrambled Eggs and Toast", description: "Simple, quick, protein-packed.", cuisine: "American", skillLevel: "Easy", timeMinutes: 10, ageRanges: ["2-5", "6-10"], dietaryFlags: ["vegetarian"], ingredients: ["Eggs", "Butter", "Toast", "Salt", "Pepper"] },

  // SOUPS
  { title: "Chicken Noodle Soup", description: "Comforting classic for any night.", cuisine: "American", skillLevel: "Easy", timeMinutes: 35, ageRanges: ["2-5", "6-10", "10-13"], dietaryFlags: [], ingredients: ["Chicken", "Egg noodles", "Carrots", "Celery", "Chicken broth"] },
  { title: "Tomato Soup with Grilled Cheese", description: "Perfect pairing for cozy nights.", cuisine: "American", skillLevel: "Easy", timeMinutes: 25, ageRanges: ["2-5", "6-10", "10-13"], dietaryFlags: ["vegetarian"], ingredients: ["Canned tomatoes", "Cream", "Butter", "Bread", "Cheese"] },
  { title: "Broccoli Cheddar Soup", description: "Creamy cheese soup kids love.", cuisine: "American", skillLevel: "Easy", timeMinutes: 30, ageRanges: ["6-10", "10-13"], dietaryFlags: ["vegetarian"], ingredients: ["Broccoli", "Cheddar cheese", "Milk", "Butter", "Flour", "Chicken broth"] },

  // MISC FAVORITES
  { title: "Hot Dogs", description: "Classic ballpark-style hot dogs.", cuisine: "American", skillLevel: "Easy", timeMinutes: 10, ageRanges: ["2-5", "6-10"], dietaryFlags: [], ingredients: ["Hot dogs", "Hot dog buns", "Ketchup", "Mustard"] },
  { title: "Corn Dogs", description: "Fun fair-style corn dogs.", cuisine: "American", skillLevel: "Intermediate", timeMinutes: 25, ageRanges: ["2-5", "6-10"], dietaryFlags: [], ingredients: ["Hot dogs", "Cornmeal batter", "Oil", "Mustard"] },
  { title: "Pizza Bagels", description: "Quick pizza snacks on bagels.", cuisine: "American", skillLevel: "Easy", timeMinutes: 15, ageRanges: ["2-5", "6-10"], dietaryFlags: ["vegetarian"], ingredients: ["Bagels", "Pizza sauce", "Mozzarella", "Pepperoni"] },
  { title: "Pigs in a Blanket", description: "Mini sausages wrapped in dough.", cuisine: "American", skillLevel: "Easy", timeMinutes: 20, ageRanges: ["2-5", "6-10"], dietaryFlags: [], ingredients: ["Mini sausages", "Crescent roll dough", "Mustard"] },
];
